[project]
name = ""
version = ""
description = ""
authors = [
    {name = "heko", email = "91366057+hkohko@users.noreply.github.com"},
]
dependencies = [
    "pytesseract>=0.3.10",
    "pre-commit>=3.5.0",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}
